# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
#parameter_name: value

services:
  #service_name:
  #    class: AppBundle\Directory\ClassName
  #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
  initialize_controller_event_listener:
    class: AppBundle\Event\EventListener\InitializeControllerEventListener
    tags:
      - { name: kernel.event_listener, event: kernel.controller_arguments, method: onKernelController }
  user.service:
    class: AppBundle\Service\UserService
    arguments: [ "@doctrine.orm.entity_manager" ]
